name: React CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        node-version: [20.x]

    steps:
    - name: Check out repository code
      uses: actions/checkout@v3

    - name: Install and use pnpm
      run: |
        cd client
        npm install -g pnpm

    - name: Restore pnpm cache
      run: |
        cd client
        pnpm install
    
    - name: Restore pnpm cache
      run: |
        cd client
        pnpm run build

    - name: Cache pnpm
      uses: actions/cache@v2
      with:
        path: ~/.pnpm-store
        key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}

    - name: Run Tests
      run: |
        cd client
        pnpm test
